#!/bin/sh
#
# Disabled hooks for this repository using jzetlen dotfiles.
(echo >&2 "$BASH_SOURCE hook disabled")
#!/bin/sh
#
# Disabled hooks for this repository using jzetlen dotfiles.
(echo >&2 "$BASH_SOURCE hook disabled")
