[settings]
experimental = true
yes = true
legacy_version_file = true
idiomatic_version_file_enable_tools = [
  "crystal",
  "elixir",
  "go",
  "java",
  "node",
  "python",
  "ruby",
  "terraform",
  "yarn"
]

[settings.npm]
bun = true

[settings.python]
uv_venv_auto = true
