[tools]
node = "lts"
neovim = "stable"
python = "3.10.14"
usage = "latest"
vim = "latest"
go = "latest"
"cargo:eza" = "0.18.17"
"cargo:starship" = "1.19.0"
"cargo:tree-sitter-cli" = "0.22.6"

[settings]
experimental = true
