[tools]
usage = "latest"
vim = "latest"
go = "latest"
"cargo:starship" = "latest"
python = "3.13"
"cargo:eza" = "0.20.4"
"cargo:tree-sitter-cli" = "0.24.3"
node = "23.0.0"
"cargo:zellij" = "latest"

[settings]
experimental = true
yes = true
legacy_version_file = true
