[tools]
neovim = "stable"
python = "3.10"
usage = "latest"
vim = "latest"
go = "latest"
"cargo:eza" = "0.18.17"
"cargo:starship" = "latest"
"cargo:tree-sitter-cli" = "0.22.6"
node = "22.7.0"

[settings]
experimental = true
yes = true
