[tools]
node = "lts"
neovim = "stable"
python = "3.10"
usage = "latest"
vim = "latest"
go = "latest"
"cargo:eza" = "0.18.17"
"cargo:starship" = "latest"
"cargo:tree-sitter-cli" = "0.22.6"
"node:@bitwarden/cli" = "latest"

[settings]
experimental = true
yes = true
