[tools]
usage = "latest"
vim = "latest"
go = "latest"
"cargo:starship" = "latest"
python = "3.13"
"cargo:eza" = "0.20.14"
"cargo:tree-sitter-cli" = "0.24.6"
node = "23.5.0"
"cargo:zellij" = "latest"
"cargo:rbw" = "latest"
gh = "latest"

[settings]
experimental = true
yes = true
legacy_version_file = true
