"$schema" = 'https://starship.rs/config-schema.json'
 
format = """
$os\
$username\
$hostname\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$nodejs\
$ruby\
$python\
$docker_context\
$c\
$deno\
$dotnet\
$golang\
$php\
$rust\
$swift\
$terraform\
$zig\
$conda\
$memory_usage\
$gcloud\
$azure\
$direnv\
$env_var\
$custom\
$sudo\
$jobs\
$battery\
$line_break\
$directory\
$status\
$character"""

right_format = "$cmd_duration$time"

palette = 'z'

command_timeout = 1000

[cmd_duration]
format = "[󱎫 $duration]($style)"
style = 'gold'

[container]
disabled = true

[directory]
read_only = " 󰌾"
truncate_to_repo = false
truncation_symbol = '…/'
style = 'blue'
repo_root_style = 'green'

[fill]
symbol = '─'
style = 'dimmed black'
disabled = true

[docker_context]
symbol = " "
format = " [$symbol$context]($style)"
disabled = true

[dotnet]
symbol = " "
format = " [$symbol$version]($style)"

[username]
style_user = 'gold'
format = '[$user]($style)@'

[git_branch]
style = 'bold green'
symbol = ""
format = '[$symbol $branch(:$remote_branch)]($style) '

[git_commit]
style = 'bold darkgreen'
only_detached = false
format = '[󰜘$hash$tag]($style) '

[git_status]
disabled = false
format = '[$all_status$ahead_behind]($style)'
conflicted = "[$count](bold yellow) "
diverged = "[$ahead_count](cyan)[󰯎](pink)[$behind_count](pink)"
staged = '[$count󰝒](bold green) '
modified = '[$count](yellow) '
untracked = '[$count](orange) '
deleted = '[$count](red) '
stashed = '[$count](purple) '
ahead = "[$count⇡](cyan) "
behind = "[$count⇣](bold red) "

[c]
symbol = " "

[golang]
symbol = " "

[hostname]
ssh_symbol = ""
format = '$hostname $ssh_symbol '

[memory_usage]
symbol = "󰍛 "

[nodejs]
symbol = " "
format = " [$symbol$version]($style)"

[os]
disabled = false
format = '$symbol'
[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Kali = " "
Linux = " "
Macos = " "
Manjaro = " "
Mint = " "
openSUSE = " "
Raspbian = " "
Redhat = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[php]
symbol = " "

[python]
symbol = " "
format = "[$symbol$version]($style)"

[ruby]
symbol = " "
format = " [$symbol$version]($style)"

[rust]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[terraform]
symbol = "󱁢 "
format = " [$symbol$version]($style)"

[time]
format = "[ $time]($style)"
time_format = "%_I:%M:%S%P"
disabled = false
style = 'gray'

[palettes.z]
black = '#282828'
red  = '#cc241d'
green = '#00AA30'
gold = '#dfad00'
purple = '#9400b6'
cyan = '#00B2B1'
darkgreen = '#006A20'
yellow = '#d7d72b'
pink = '#e85587'
gray = '#738888'
