"$schema" = "https://starship.rs/config-schema.json"

format = """
$os\
$username\
$hostname\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$nodejs\
$ruby\
$python\
$docker_context\
$c\
$deno\
$dotnet\
$golang\
$php\
$rust\
$swift\
$terraform\
$zig\
$conda\
$memory_usage\
$gcloud\
$azure\
$direnv\
$env_var\
$custom\
$sudo\
$jobs\
$battery\
$cmd_duration\
$time\
$line_break\
$directory\
$status\
$character"""

right_format = ""

palette = 'z'

command_timeout = 1000

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
symbol = "AWS "
style = "bold yellow"
disabled = false
expiration_symbol = "X"
force_display = false

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"
disabled = false

[cmd_duration]
min_time = 2000
format = '\[[took $duration]($style)\]'
style = "yellow bold"
show_milliseconds = false
disabled = false
show_notifications = false
min_time_to_notify = 45000

[container]
format = '[$symbol \[$name\]]($style) '
symbol = "container"
disabled = false

[directory]
read_only = " ro"
truncate_to_repo = false
truncation_symbol = '.../'
style = 'blue'
repo_root_style = 'green'

[docker_context]
disabled = true

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'
symbol = "GCP"
disabled = false

[gcloud.region_aliases]

[gcloud.project_aliases]

[git_branch]
style = 'bold green'
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = "on "

[git_commit]
style = 'bold darkgreen'
only_detached = false
format = '[$hash$tag]($style) '

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[git_status]
disabled = false
format = '[$all_status$ahead_behind]($style)'
conflicted = "[$count cfl](bold yellow) "
diverged = "[$ahead_count ahe](cyan) [$behind_count beh](pink) "
staged = '[$count stg](bold green) '
modified = '[$count mod](yellow) '
renamed = '[$count ren](gold) '
untracked = '[$count unt](orange) '
deleted = '[$count del](red) '
stashed = '[$count sta](purple) '
ahead = "[$count ahe](cyan) "
behind = "[$count beh](pink) "

[golang]
format = '\[[$symbol($version)]($style)\]'
version_format = "v${raw}"
symbol = "go "
style = "bold cyan"
disabled = false
not_capable_style = "bold red"
detect_extensions = ["go"]
detect_files = [
    "go.mod",
    "go.sum",
    "go.work",
    "glide.yaml",
    "Gopkg.yml",
    "Gopkg.lock",
    ".go-version",
]
detect_folders = ["Godeps"]
[helm]
format = '\[[$symbol($version)]($style)\]'
version_format = "v${raw}"
symbol = "helm "
style = "bold white"
disabled = false
detect_extensions = []
detect_files = [
    "helmfile.yaml",
    "Chart.yaml",
]
detect_folders = []

[hostname]
ssh_only = true
ssh_symbol = "ssh to "
trim_at = "."
detect_env_vars = []
format = "[$ssh_symbol$hostname]($style) in "
style = "green dimmed bold"
disabled = false

[jobs]
threshold = 1
symbol_threshold = 1
number_threshold = 2
format = "[$number bg]($style) "
symbol = ""
style = "bold blue"
disabled = false

[kotlin]
format = '\[[$symbol($version)]($style)\]'
version_format = "v${raw}"
symbol = "kotlin "
style = "bold blue"

[line_break]
disabled = false


[nodejs]
format = '\[[$symbol($version)]($style)\]'
version_format = "v${raw}"
symbol = "node "
style = "bold green"
disabled = false
not_capable_style = "bold red"
detect_extensions = [
    "js",
    "mjs",
    "cjs",
    "ts",
    "mts",
    "cts",
]
detect_files = [
    "package.json",
    ".node-version",
    ".nvmrc",
]
detect_folders = ["node_modules"]

[os]
disabled = true

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
symbol = "py "

[ruby]
format = '\[[$symbol($version)]($style)\]'
symbol = "ruby "
disabled = false

[rust]
format = '\[[$symbol($version)]($style)\]'
symbol = "rust "

[terraform]
format = '\[[$symbol$workspace]($style)\]'
symbol = "tf "

[username]
style_user = 'gold'
format = '\[[$user]($style)\]'

[time]
format = "[$time]($style)"
time_format = "%_I:%M:%S%P"
disabled = false
style = 'gray'

[palettes.z]
black = '#282828'
red  = '#cc241d'
green = '#00AA30'
gold = '#dfad00'
purple = '#9400b6'
cyan = '#00B2B1'
darkgreen = '#006A20'
yellow = '#d7d72b'
pink = '#e85587'
gray = '#738888'
