"$schema" = 'https://starship.rs/config-schema.json'
 
format = """
$os\
$username\
$hostname\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$cmd_duration\
$time\
$line_break\
$directory\
$status\
$character"""

right_format = """
$docker_context\
$c\
$deno\
$dotnet\
$golang\
$nodejs\
$php\
$python\
$ruby\
$rust\
$swift\
$terraform\
$zig\
$conda\
$memory_usage\
$gcloud\
$azure\
$direnv\
$env_var\
$custom\
$sudo\
$jobs\
$battery"""

[cmd_duration]
format = "[󱎫 $duration]($style)"

[container]
disabled = true

[directory]
read_only = " 󰌾"
truncate_to_repo = false
truncation_symbol = '…/'

[fill]
symbol = '─'
style = 'dimmed black'

[docker_context]
symbol = " "

[username]
format = '[$user]($style)@'

[git_branch]
symbol = ""
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_commit]
only_detached = false
format = '[󰜘$hash$tag]($style) '

[git_status]
disabled = false
format = '[$all_status$ahead_behind]($style)'
staged = '[+$count](bold green) '
modified = '[!$count](yellow) '
untracked = '[?$count](orange) '
stashed = '[*$count](bold gray) '


# icons

[c]
symbol = " "

[golang]
symbol = " "

[hostname]
ssh_symbol = ""
format = '$ssh_symbol$hostname '

[memory_usage]
symbol = "󰍛 "

[nodejs]
symbol = ""
format = "[$symbol$version]($style)"

[os]
disabled = false
format = '$symbol'
[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Kali = " "
Linux = " "
Macos = " "
Manjaro = " "
Mint = " "
openSUSE = " "
Raspbian = " "
Redhat = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[php]
symbol = " "

[python]
symbol = " "
format = "[$symbol$version]($style)"

[ruby]
symbol = ""
format = "[$symbol$version]($style)"

[rust]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[time]
format = " $time"
time_format = "%_I:%M:%S%P"
disabled = false
